cidr_scope       = "my_cidr"
extra_cidr       = "37.19.211.0/24"
ami_name_pattern = "ubuntu-pro-server/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-pro-server-"
# ami_name_pattern = "RHEL-9.3.0_HVM-"
# ami_name_pattern = "amzn2-"
aws_secret_name = "Plaid_Credentials_0"
